import './ManageItem.css';
export function ManageItem() {
    return (
        <div className="p-2 text-center">
            <h1 className="text-2xl font-bold pb-2">Manage Items</h1>
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Bugatti_Chiron_1.jpg/800px-Bugatti_Chiron_1.jpg"
                 alt="Dashboard Image"/>
            <p className="mt-2">
                <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut, corporis cum doloribus error exercitationem impedit maxime necessitatibus odio repellendus ullam. Beatae consequatur ex itaque iure magnam perferendis ratione rem vel?</span><span>Consequatur est ipsum iste, laborum modi non nostrum perferendis quam quia voluptate. Accusamus amet architecto beatae consequatur earum error esse facilis laudantium magnam nihil nulla quae sit, sunt ut vero.</span><span>Architecto delectus eligendi illum, nemo officia possimus quae quo repudiandae sequi voluptatum. Accusamus aliquid asperiores cumque ut. A ad, blanditiis consectetur doloribus eaque minima porro recusandae repellat sapiente unde vitae.</span><span>Incidunt ipsa laborum odio quam quod vel vitae. Consequatur dicta dolores fuga labore, magni minima nihil quaerat quam quasi recusandae velit voluptatem. Dicta excepturi explicabo impedit in officiis reprehenderit vitae.</span><span>A ab, commodi consectetur deleniti dignissimos dolorem doloribus dolorum eligendi et exercitationem ipsam magnam maiores obcaecati, omnis placeat praesentium quae quibusdam quo sed similique temporibus ut voluptas voluptate voluptates, voluptatibus?</span><span>A ducimus est hic illo labore magnam minima nisi nostrum pariatur totam? Adipisci deserunt eos incidunt magnam officia omnis quia sed similique. At facilis itaque nemo nobis qui vero voluptatem?</span><span>At consectetur cumque doloremque dolores, ea excepturi illo in incidunt ipsam ipsum magnam obcaecati odit omnis optio, provident quis, repellat rerum sint suscipit unde? Alias itaque nesciunt sit tenetur veritatis.</span><span>Ad corporis ducimus earum exercitationem expedita iste minima non nostrum obcaecati perspiciatis quaerat, quasi quo saepe sint, unde ut, voluptate voluptatem? Adipisci blanditiis fuga inventore odit omnis quibusdam soluta velit.</span><span>Aperiam asperiores atque autem eos excepturi expedita fugiat hic magni, nisi recusandae reprehenderit similique velit voluptatum. Animi atque, corporis culpa cum dolor eveniet exercitationem fugit ipsa laudantium, nulla, totam vel.</span><span>Aliquam architecto cupiditate fugiat magni molestiae molestias provident, quaerat quam quis repellendus similique vero vitae voluptatem? Debitis dolorem dolores in labore quidem! Itaque laudantium magni nam rem sint? Dolorem, quos.</span>
            </p>
        </div>
    );
}